default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - jacky06/metrics-server:v0.5.2
  - rancher/mirrored-flannelcni-flannel:v0.16.3
  - registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.23.6
